alz_app_api_cliente_get:
    path:     /cliente
    defaults: { _controller: AlzAppBundle:Api:clienteGet }
    methods: GET
    requirements:
        _format: json

alz_app_api_cliente_post:
    path:     /cliente
    defaults: { _controller: AlzAppBundle:Api:clientePost }
    methods: PUT 
    requirements:
        _format: json

alz_app_api_facturaconceptos_get:
    path:     /factura-conceptos
    defaults: { _controller: AlzAppBundle:Api:FacturaconceptosGet }
    methods: GET
    requirements:
        _format: json

alz_app_api_facturaconcepto_delete:
    path:     /factura-concepto/{id}
    defaults: { _controller: AlzAppBundle:Api:FacturaconceptoDelete }
    methods: DELETE
    requirements:
        _format: json

alz_app_api_facturaconcepto_put:
    path:     /factura-concepto
    defaults: { _controller: AlzAppBundle:Api:FacturaconceptoPut }
    methods: PUT
    requirements:
        _format: json
