alz_app:
    resource: "@AlzAppBundle/Resources/config/routing-cliente.yml"
    prefix:   /cliente

alz_app_homepage:
    path:     /
    defaults: { _controller: AlzAppBundle:Default:index }

alz_app_facturas:
    path: /facturas
    defaults: { _controller: AlzAppBundle:Default:facturas }

alz_app_factura:
    path: /factura
    defaults: { _controller: AlzAppBundle:Default:factura }

alz_app_configuracion:
    path: /configuracion
    defaults: { _controller: AlzAppBundle:Default:configuracion }

alz_app_configuracion_editar:
    path: /configuracion-editar
    defaults: { _controller: AlzAppBundle:Default:configuracionEditar }
