alz_app_api:
    resource: "@AlzAppBundle/Resources/config/routing-api.yml"
    prefix:   /api

alz_app_factura:
    resource: "@AlzAppBundle/Resources/config/routing-factura.yml"
    prefix:   /factura

alz_app_cliente:
    resource: "@AlzAppBundle/Resources/config/routing-cliente.yml"
    prefix:   /cliente

alz_app_empresa:
    resource: "@AlzAppBundle/Resources/config/routing-empresa.yml"
    prefix:   /empresa

alz_app_homepage:
    path:     /
    defaults: { _controller: AlzAppBundle:Default:index }

alz_app_premium_comprar:
    path:     /premium/comprar/
    defaults: { _controller: AlzAppBundle:Default:premiumComprar }

alz_app_premium_cancelar:
    path:     /premium/cancelar/
    defaults: { _controller: AlzAppBundle:Default:premiumCancelar }

alz_app_premium_paypal_cancelar:
    path:     /premium/paypal-cancelar/
    defaults: { _controller: AlzAppBundle:Default:premiumPaypalCancelar }

alz_app_premium_paypal_ok:
    path:     /premium/paypal-ok/
    defaults: { _controller: AlzAppBundle:Default:premiumPaypalOk }
