services:
    app.tokens.action_listener:
        class: Alz\AppBundle\EventListener\AppListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
