Alz\AppBundle\Entity\Empresa:
    properties:
        nombre: 
            - NotBlank: ~
        cif: 
            - NotBlank: ~
        direccion1: 
            - NotBlank: ~
        ciudad: 
            - NotBlank: ~
        telefono: 
            - NotBlank: ~
        nombre: 
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

Alz\AppBundle\Entity\Cliente:
    properties:
        nombre: 
            - NotBlank: ~
        cif: 
            - NotBlank: ~
        direccion1: 
            - NotBlank: ~
        cp: 
            - NotBlank: ~
        ciudad: 
            - NotBlank: ~
        email:
            - Email: ~

Alz\AppBundle\Entity\FacturaConcepto:
    properties:
        nombre:
            - NotBlank: ~
        precio:
            - NotBlank: ~
            #- Type: number
        cantidad:
            - NotBlank: ~
            - Type: integer
        iva:
            - NotBlank: ~
            - Type: integer
