alz_app:
    resource: "@AlzAppBundle/Resources/config/routing.yml"
    prefix:   /app

alz_web:
    resource: "@AlzWebBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user
